using System.Net;
using System.Text;

namespace Bmd.Output;

/// <summary>One endpoint on a device — an input, an output, a multiviewer window, an auxiliary.
/// <paramref name="Id"/> is unique across the whole page, because the browser needs to address
/// them all from one script.</summary>
public sealed record DiagramNode(string Id, string Badge, string Label);

/// <summary>A signal path inside one device: this source currently reaches that destination.</summary>
public sealed record DiagramLink(string From, string To);

/// <summary>One device's contribution to the page. <paramref name="Error"/> is set instead of the
/// rest when the device could not be reached — a diagram of a network is more useful with a gap
/// marked in it than with the device silently missing.</summary>
public sealed record DiagramDevice(
    string Title, string Subtitle, string Kind, string Host,
    IReadOnlyList<DiagramNode> Sources, IReadOnlyList<DiagramNode> Destinations,
    IReadOnlyList<DiagramLink> Links, IReadOnlyList<string> Facts, string? Error = null);

/// <summary>Renders every device bmd can reach as one self-contained HTML page.
///
/// <para><b>Self-contained means one file, not no script.</b> The page is emailed, opened from a
/// USB stick in a rack room, or printed and taped inside a cabinet door, so it fetches nothing:
/// no CDN, no web font, no external stylesheet. Its script and styles are inline, which costs
/// none of that and buys the thing a generator cannot do on its own — measure the laid-out page
/// and draw connectors between real positions, then light them up under the cursor.</para>
///
/// <para>Everything interpolated here is device-supplied text: an operator can name an input
/// <c>&lt;script&gt;</c> from a front panel, and this page opens in a browser. All of it goes
/// through <see cref="Text"/>, and the link data is emitted as JSON inside a
/// <c>&lt;script type="application/json"&gt;</c> block rather than as executable source, so a
/// label can never become code.</para></summary>
public static class Diagram
{
    public static string Render(IReadOnlyList<DiagramDevice> devices, DateTimeOffset generatedAt)
    {
        var page = new StringBuilder();
        var reachable = devices.Where(d => d.Error is null).ToList();

        page.Append($"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Signal flow</title>
            <style>
            {Css}
            </style>
            </head>
            <body>
            <main>
              <header class="top">
                <p class="eyebrow">Signal flow</p>
                <h1>{reachable.Count} device{(reachable.Count == 1 ? "" : "s")}</h1>
                <p class="stamp">As at {Text(generatedAt.ToString("yyyy-MM-dd HH:mm"))} UTC &middot; hover to trace a signal, click to keep it, Esc to clear</p>
              </header>

            """);

        foreach (var device in devices) AppendDevice(page, device);

        page.Append($"""
              <footer>Generated by bmd. Locks, and anything changed after the timestamp, are not shown.
              Connections are those inside each device; cabling between devices is not something a
              device reports.</footer>
            </main>
            <script>
            {Script}
            </script>
            </body>
            </html>

            """);

        return page.ToString();
    }

    static void AppendDevice(StringBuilder page, DiagramDevice device)
    {
        page.Append($"""
              <section class="device" data-kind="{Text(device.Kind)}">
                <header>
                  <h2>{Text(device.Title)}</h2>
                  <p class="sub">{Text(device.Subtitle)} &middot; {Text(device.Host)}</p>
                </header>

            """);

        if (device.Error is not null)
        {
            page.Append($"""
                <p class="unreachable">{Text(device.Error)}</p>
              </section>

            """);
            return;
        }

        if (device.Facts.Count > 0)
        {
            page.Append("    <ul class=\"facts\">\n");
            foreach (var fact in device.Facts)
                page.Append($"      <li>{Text(fact)}</li>\n");
            page.Append("    </ul>\n");
        }

        var fanOut = device.Links.GroupBy(l => l.From).ToDictionary(g => g.Key, g => g.Count());

        page.Append("""
                <div class="flow">
                  <ul class="col srcs">

            """);
        foreach (var node in device.Sources)
        {
            var fan = fanOut.GetValueOrDefault(node.Id, 0);
            page.Append($"""
                      <li data-node="{Text(node.Id)}" tabindex="0"><span class="num">{Text(node.Badge)}</span><span class="lbl">{Text(node.Label)}</span><span class="fan">{fan}</span></li>

                """);
        }

        page.Append("""
                  </ul>
                  <svg class="wires" aria-hidden="true"></svg>
                  <ul class="col dsts">

            """);
        foreach (var node in device.Destinations)
        {
            page.Append($"""
                      <li data-node="{Text(node.Id)}" tabindex="0"><span class="num">{Text(node.Badge)}</span><span class="lbl">{Text(node.Label)}</span></li>

                """);
        }

        // Links travel as data, never as generated script: a device label is untrusted text and
        // must not be able to reach a place where it would be parsed as code.
        page.Append($"""
                  </ul>
                </div>
                <script type="application/json" class="wire-data">{LinksJson(device.Links)}</script>
              </section>

            """);
    }

    /// <summary>Hand-built rather than serialized: the payload is two short strings per link, the
    /// ids are generated here so their shape is known, and this keeps the page's data out of the
    /// JSON source-generator contract that exists for command output.</summary>
    static string LinksJson(IReadOnlyList<DiagramLink> links)
    {
        var json = new StringBuilder("[");
        for (var i = 0; i < links.Count; i++)
        {
            if (i > 0) json.Append(',');
            json.Append($"[\"{Json(links[i].From)}\",\"{Json(links[i].To)}\"]");
        }
        return json.Append(']').ToString();
    }

    /// <summary>Ids are generated (`d0-in-3`), so this only has to be correct, not general.
    /// <c>&lt;/</c> is escaped because the string sits inside a script element.</summary>
    static string Json(string value)
    {
        var escaped = new StringBuilder();
        foreach (var c in value)
        {
            if (c is '"' or '\\') escaped.Append('\\').Append(c);
            else if (c == '<') escaped.Append("\\u003c");
            else if (c < ' ') escaped.Append($"\\u{(int)c:x4}");
            else escaped.Append(c);
        }
        return escaped.ToString();
    }

    static string Text(string value) => WebUtility.HtmlEncode(value);

    const string Css = """
        :root {
          --bg: #0c0d10; --panel: #14161a; --line: #24272e; --line-soft: #1c1f25;
          --fg: #e6e8ec; --dim: #989fab; --faint: #79818e; --signal: #f2542d;
          --mono: "IBM Plex Mono", ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", monospace;
          --sans: "IBM Plex Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }
        * { box-sizing: border-box; }
        body { margin: 0; background: var(--bg); color: var(--fg); font-family: var(--sans); line-height: 1.5; }
        main { max-width: 78rem; margin: 0 auto; padding: 2.5rem 1.25rem 4rem; }
        .eyebrow { margin: 0 0 .4rem; font-family: var(--mono); font-size: .68rem; font-weight: 600;
          letter-spacing: .2em; text-transform: uppercase; color: var(--faint); }
        h1 { margin: 0; font-size: clamp(1.8rem, 4vw, 2.6rem); line-height: 1.05; letter-spacing: -.02em; }
        .stamp { margin: .45rem 0 0; font-family: var(--mono); font-size: .76rem; color: var(--faint); }
        .device { margin-top: 3rem; padding-top: 2rem; border-top: 1px solid var(--line-soft); }
        .device h2 { margin: 0; font-size: 1.45rem; letter-spacing: -.01em; }
        .device .sub { margin: .2rem 0 0; color: var(--dim); font-size: .92rem; }
        .facts { list-style: none; display: flex; flex-wrap: wrap; gap: .4rem; margin: .9rem 0 0; padding: 0; }
        .facts li { font-family: var(--mono); font-size: .68rem; letter-spacing: .04em; color: var(--faint);
          border: 1px solid var(--line); border-radius: 5px; padding: .18rem .45rem; }
        .unreachable { margin: 1rem 0 0; padding: .8rem 1rem; border: 1px solid var(--line);
          border-left: 2px solid var(--signal); border-radius: 8px; background: var(--panel); color: var(--dim); }
        /* The gutter is where the diagram actually happens, so it gets the leftover width rather
           than a share of it. Label columns are capped instead of flexible: as `1fr` they took
           roughly 28rem each on a wide screen and squeezed the connectors into a bundle, when a
           label like "Streaming Pro Presenter" needs about 15. Cap them and the wires get
           everything else. */
        .flow { position: relative; display: grid;
          grid-template-columns: minmax(7rem, 16rem) minmax(6rem, 1fr) minmax(7rem, 16rem);
          gap: 0; margin-top: 1.25rem; align-items: start; }
        /* Absolutely positioned, so it is OUT of the grid flow. That is the point — it overlays
           the whole diagram — but it also means the grid has only two in-flow children, and
           without the explicit placement below the destination column falls into the middle
           track and the third is left empty. Measured, not assumed: the tracks came out
           256/696/256 with the destinations sitting in the 696 and no gutter at all. */
        .wires { position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none; overflow: visible; }
        .srcs { grid-column: 1; }
        .dsts { grid-column: 3; }
        .wires path { fill: none; stroke: var(--line); stroke-width: 1.25; transition: stroke .12s, opacity .12s; }
        .wires path.lit { stroke: var(--signal); stroke-width: 2; }
        .flow.tracing .wires path:not(.lit) { opacity: .18; }
        .col { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: .25rem; }
        /* Set by the script when one column is much shorter than the other: 18 sources feeding 40
           destinations otherwise crowd into the top third and every line leaves at the same steep
           angle. Spread over the same height, the fan is readable. */
        .col.spread { gap: 0; justify-content: space-between; }
        .col li { display: flex; align-items: baseline; gap: .5rem; padding: .3rem .55rem;
          border: 1px solid transparent; border-radius: 7px; cursor: pointer;
          transition: background .12s, border-color .12s; }
        .col li:hover, .col li:focus-visible { outline: none; background: var(--panel); border-color: var(--line); }
        .col li.lit { background: var(--panel); border-color: var(--signal); }
        /* A pin outlives the cursor, so it needs to be legible without one: the marker is what
           tells you the highlight is being held rather than merely hovered. */
        .col li.pinned { background: var(--panel); border-color: var(--signal); }
        .col li.pinned .num { background: var(--signal); color: #0c0d10; border-color: var(--signal); }
        .wires path.pinned { stroke: var(--signal); stroke-width: 2.25; }
        .flow.tracing .col li:not(.lit) { opacity: .3; }
        .srcs li { justify-content: flex-start; }
        /* Mirrored, but packed toward the gutter rather than away from it. With row-reverse the
           main axis runs right-to-left, so flex-end is the left edge — which is where the wires
           arrive. Right-aligning instead put the text at the far side of the column, a whole
           track away from the line pointing at it. */
        .dsts li { flex-direction: row-reverse; justify-content: flex-end; text-align: left; }
        .num { font-family: var(--mono); font-size: .64rem; letter-spacing: .05em; color: var(--signal);
          border: 1px solid var(--line); border-radius: 4px; padding: .08rem .3rem; white-space: nowrap;
          font-variant-numeric: tabular-nums; flex: none; }
        /* Never flex: 1. A label that stretches to fill its column pins that grid track to its
           maximum however short the text is, and the gutter — the only column that actually wants
           the space — gets whatever is left. Sized to content, the tracks shrink and the diagram
           grows. */
        .lbl { font-size: .92rem; flex: 0 1 auto; min-width: 0;
          overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        /* Auto margin rather than a flexible label: it pushes the count to the far edge without
           making the track wide enough to hold it there. */
        .fan { font-family: var(--mono); font-size: .64rem; color: var(--faint); flex: none;
          margin-left: auto; padding-left: .5rem; font-variant-numeric: tabular-nums; }
        footer { margin-top: 3.5rem; padding-top: 1rem; border-top: 1px solid var(--line-soft);
          color: var(--faint); font-size: .8rem; max-width: 52rem; }
        @media (max-width: 46rem) {
          .flow { grid-template-columns: 1fr; gap: 1rem; }
          .wires { display: none; }
          .dsts li { flex-direction: row; text-align: left; }
        }
        @media (prefers-reduced-motion: reduce) { * { transition: none !important; } }
        @media print {
          body { background: #fff; color: #000; }
          .col li, .facts li, .unreachable { background: transparent; }
          .num { color: #000; }
          .wires path { stroke: #999; }
        }
        """;

    /// <summary>Draws the connectors and traces them on hover.
    ///
    /// The generator cannot place these: where a row lands depends on the font that resolved, the
    /// viewport, and how long the labels are. So the page measures itself after layout and again
    /// on resize. Without the script the columns still read correctly — the wires are the
    /// enhancement, not the content.</summary>
    const string Script = """
        (function () {
          var SVG = "http://www.w3.org/2000/svg";

          function build(section) {
            var flow = section.querySelector(".flow");
            var svg = section.querySelector(".wires");
            var data = section.querySelector(".wire-data");
            if (!flow || !svg || !data) return null;

            var links;
            try { links = JSON.parse(data.textContent); } catch (e) { return null; }

            var byNode = {};
            var paths = [];

            function draw() {
              while (svg.firstChild) svg.removeChild(svg.firstChild);
              paths.length = 0;
              for (var k in byNode) delete byNode[k];

              spread();

              var box = flow.getBoundingClientRect();
              svg.setAttribute("viewBox", "0 0 " + box.width + " " + box.height);

              links.forEach(function (pair) {
                var a = flow.querySelector('[data-node="' + cssEscape(pair[0]) + '"]');
                var b = flow.querySelector('[data-node="' + cssEscape(pair[1]) + '"]');
                if (!a || !b) return;

                var ra = a.getBoundingClientRect(), rb = b.getBoundingClientRect();
                var x1 = ra.right - box.left, y1 = ra.top + ra.height / 2 - box.top;
                var x2 = rb.left - box.left, y2 = rb.top + rb.height / 2 - box.top;
                var bend = Math.max(24, (x2 - x1) / 2);

                var path = document.createElementNS(SVG, "path");
                path.setAttribute("d",
                  "M" + x1 + "," + y1 + " C" + (x1 + bend) + "," + y1 +
                  " " + (x2 - bend) + "," + y2 + " " + x2 + "," + y2);
                svg.appendChild(path);

                var record = { path: path, from: pair[0], to: pair[1] };
                paths.push(record);
                (byNode[pair[0]] = byNode[pair[0]] || []).push(record);
                (byNode[pair[1]] = byNode[pair[1]] || []).push(record);
              });
            }

            // Stretch the shorter column to the taller one's height so the connectors fan across
            // the whole diagram instead of bunching. Measured rather than calculated: the columns
            // hold wrapped text whose height depends on the font that actually resolved.
            function spread() {
              var srcs = flow.querySelector(".srcs");
              var dsts = flow.querySelector(".dsts");
              if (!srcs || !dsts) return;

              srcs.classList.remove("spread");
              dsts.classList.remove("spread");
              srcs.style.height = "";
              dsts.style.height = "";
              if (window.matchMedia && window.matchMedia("(max-width: 46rem)").matches) return;

              var a = srcs.getBoundingClientRect().height;
              var b = dsts.getBoundingClientRect().height;
              // Only worth doing when the difference is real; stretching by a few pixels just
              // makes the row spacing look accidental.
              if (Math.abs(a - b) < 24) return;

              var shorter = a < b ? srcs : dsts;
              shorter.style.height = Math.max(a, b) + "px";
              shorter.classList.add("spread");
            }

            // Hover previews, a click keeps it. Hovering while something is pinned previews over
            // the top and falls back to the pin on the way out, which is what makes it possible to
            // compare two paths without losing the one you were looking at.
            var pinned = null;
            var hovered = null;

            function show() {
              var id = hovered || pinned;
              var lit = byNode[id] || [];

              flow.classList.toggle("tracing", !!id);
              paths.forEach(function (r) { r.path.classList.remove("lit", "pinned"); });
              Array.prototype.forEach.call(flow.querySelectorAll("li"), function (li) {
                li.classList.remove("lit", "pinned");
              });
              if (!id) return;

              var held = id === pinned;
              lit.forEach(function (r) {
                r.path.classList.add(held ? "pinned" : "lit");
                [r.from, r.to].forEach(function (n) {
                  var el = flow.querySelector('[data-node="' + cssEscape(n) + '"]');
                  if (el) el.classList.add("lit");
                });
              });
              var anchor = flow.querySelector('[data-node="' + cssEscape(id) + '"]');
              if (anchor && held) anchor.classList.add("pinned");
            }

            function togglePin(id) {
              pinned = pinned === id ? null : id;
              show();
            }

            Array.prototype.forEach.call(flow.querySelectorAll("li[data-node]"), function (li) {
              var id = li.getAttribute("data-node");
              li.addEventListener("mouseenter", function () { hovered = id; show(); });
              li.addEventListener("mouseleave", function () { hovered = null; show(); });
              li.addEventListener("focus", function () { hovered = id; show(); });
              li.addEventListener("blur", function () { hovered = null; show(); });
              li.addEventListener("click", function () { togglePin(id); });
              li.addEventListener("keydown", function (e) {
                // Enter and Space are what a focused control is expected to answer to; without
                // this the pin would be mouse-only while the trace itself is not.
                if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
                  e.preventDefault();
                  togglePin(id);
                }
              });
            });

            // Clicking the empty space around the diagram clears the pin, which is the gesture
            // people try before they look for a way to undo it.
            flow.addEventListener("click", function (e) {
              if (!e.target.closest("li[data-node]")) { pinned = null; show(); }
            });

            // On the document, not the section: a keydown lands on whatever has focus and bubbles
            // up from there, so a listener on the section only ever hears it when focus happens to
            // be inside that section. Clicking a node does focus it, so this mostly worked - which
            // is the worst kind of not working.
            document.addEventListener("keydown", function (e) {
              if (e.key === "Escape" && pinned) { pinned = null; show(); }
            });

            return draw;
          }

          // Ids are generated by bmd and contain only [a-z0-9-], but the attribute selector is
          // built by string concatenation, so escape anyway rather than rely on that holding.
          function cssEscape(value) {
            return window.CSS && CSS.escape ? CSS.escape(value) : value.replace(/["\\]/g, "\\$&");
          }

          var redraws = [];
          Array.prototype.forEach.call(document.querySelectorAll(".device"), function (section) {
            var draw = build(section);
            if (draw) redraws.push(draw);
          });

          function drawAll() { redraws.forEach(function (d) { d(); }); }
          drawAll();
          // Fonts land after first paint and move every row; redraw once they have.
          if (document.fonts && document.fonts.ready) document.fonts.ready.then(drawAll);
          window.addEventListener("resize", drawAll);
        })();
        """;
}
